### PR TITLE
Add rst_n to pond again

### PR DESCRIPTION
**Pull request by mbstrange2**
We need to enable just adding flush instead of rst_n/

### CODE REVIEW

**Review by ankita0805 — APPROVED** [review]

**Comment by ankita0805** [comment]
We can keep both rst_n and flush. Area delta is insignificant.

**Comment by mbstrange2** [comment]
Ankita's experiments show

Area w/o rst_n,flush = 5966 (92.52 x 87.552)
Area w/ rst_n, flush = 6071 (94.23 * 87.552)

**Comment by ankita0805** [comment]
Alex will confirm if the above area delta is okay (baseline vs w/ rst & flush) . By doing only flush instead of flush & rst, the area delta is not significant.

**Comment by alexcarsello** [comment]
It looks like we can accept this area increase, but it's getting close.

**Pull request merged**
